name: Lovefield-TS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - shell: bash
        env:
          SUPER_SECRET: $${{ secrets.SAUCE_USERNAME }}
        run:
          echo "$SUPER_SECRET"
      
      - uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accesskey: ${{ secrets.SAUCE_ACCESSKEY }}
          tunnelIdentifier: github-action-tunnel
          scVersion: 4.6.4
      - run: npm install
      - run: npx gulp ci
      - run: npx eslint --quiet **/*.ts
